spring.application.name=Security
 # configuracion de seguridad
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
#Config de JWT
security.jwt.private.key=${PRIVATE_KEY}
#Acá puedo "inventar" el "nombre de usuario" que quiera
security.jwt.user.generator=${USER_GENERATOR}

# configuracion de base de datos

# Configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialec
# mirar consultas sql
spring.jpa.show-sql=true
# esto es realiza el formato para las sql
spring.jpa.properties.hibernate.format_sql=true
